-- MySQL Script generated by MySQL Workbench
-- Fri Apr 14 07:54:16 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `Id` INT NOT NULL,
  `Nombre` VARCHAR(255) NOT NULL,
  `Direccion` VARCHAR(32) NULL,
  `Ciudad` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `Telefono` INT NOT NULL,
  `Codigo_interno` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `mydb`.`Carros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carros` (
  `Matricula` INT NOT NULL,
  `Marca` VARCHAR(255) NOT NULL,
  `Modelo` VARCHAR(255) NOT NULL,
  `Color` VARCHAR(255) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Precio` DECIMAL(255) NOT NULL,
  PRIMARY KEY (`Matricula`));


-- -----------------------------------------------------
-- Table `mydb`.`Revision`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Revision` (
  `Id` INT NOT NULL,
  `Cambio_F` BLOB NOT NULL,
  `Cambio_A` BLOB NOT NULL,
  `Cambio_F` BLOB NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Otros` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `mydb`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Compra` (
  `Clientes_Id` INT NOT NULL,
  `Carros_Matricula` INT NOT NULL,
  PRIMARY KEY (`Clientes_Id`, `Carros_Matricula`),
  INDEX `fk_Clientes_has_Carros_Carros1_idx` (`Carros_Matricula` ASC) VISIBLE,
  INDEX `fk_Clientes_has_Carros_Clientes_idx` (`Clientes_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Clientes_has_Carros_Clientes`
    FOREIGN KEY (`Clientes_Id`)
    REFERENCES `mydb`.`Clientes` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clientes_has_Carros_Carros1`
    FOREIGN KEY (`Carros_Matricula`)
    REFERENCES `mydb`.`Carros` (`Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Pasan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pasan` (
  `Carros_Matricula` INT NOT NULL,
  `Revision_Id` INT NOT NULL,
  PRIMARY KEY (`Carros_Matricula`, `Revision_Id`),
  INDEX `fk_Carros_has_Revision_Revision1_idx` (`Revision_Id` ASC) VISIBLE,
  INDEX `fk_Carros_has_Revision_Carros1_idx` (`Carros_Matricula` ASC) VISIBLE,
  CONSTRAINT `fk_Carros_has_Revision_Carros1`
    FOREIGN KEY (`Carros_Matricula`)
    REFERENCES `mydb`.`Carros` (`Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carros_has_Revision_Revision1`
    FOREIGN KEY (`Revision_Id`)
    REFERENCES `mydb`.`Revision` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
