-- MySQL Script generated by MySQL Workbench
-- Fri Apr 14 07:55:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `DNI` INT NOT NULL,
  `Nombre` VARCHAR(255) NOT NULL,
  `Apellido` VARCHAR(32) NOT NULL,
  `Direccion` VARCHAR(255) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Fecha_Nacimiento` DATETIME NULL,
  PRIMARY KEY (`DNI`));


-- -----------------------------------------------------
-- Table `mydb`.`Proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveedores` (
  `NIF` INT NOT NULL,
  `Nombre` VARCHAR(255) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`NIF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Productos` (
  `Codigo` INT NOT NULL,
  `Nombre` VARCHAR(255) NOT NULL,
  `Precio` DECIMAL(45) NOT NULL,
  `Proveedores_NIF` INT NOT NULL,
  PRIMARY KEY (`Codigo`, `Proveedores_NIF`),
  INDEX `fk_Productos_Proveedores1_idx` (`Proveedores_NIF` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_Proveedores1`
    FOREIGN KEY (`Proveedores_NIF`)
    REFERENCES `mydb`.`Proveedores` (`NIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`compra` (
  `Cliente_DNI` INT NOT NULL,
  `Productos_Codigo` INT NOT NULL,
  PRIMARY KEY (`Cliente_DNI`, `Productos_Codigo`),
  INDEX `fk_Cliente_has_Productos_Productos1_idx` (`Productos_Codigo` ASC) VISIBLE,
  INDEX `fk_Cliente_has_Productos_Cliente1_idx` (`Cliente_DNI` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_has_Productos_Cliente1`
    FOREIGN KEY (`Cliente_DNI`)
    REFERENCES `mydb`.`Cliente` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Productos_Productos1`
    FOREIGN KEY (`Productos_Codigo`)
    REFERENCES `mydb`.`Productos` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
