-- MySQL Script generated by MySQL Workbench
-- Wed Apr 12 06:46:18 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estudiantes` (
  `Codigo` INT NOT NULL,
  `Nombre` VARCHAR(16) NOT NULL,
  `Apellido` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Codigo`));


-- -----------------------------------------------------
-- Table `mydb`.`Asignaturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Asignaturas` (
  `Codigo_A` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Codigo_A`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Notas` (
  `Id` INT NOT NULL,
  `Nota1` INT NOT NULL,
  `Nota2` INT NOT NULL,
  `Nota3` INT NOT NULL,
  `Promedio` INT NOT NULL,
  `Id_estudiante` INT NOT NULL,
  `Asignaturas_Codigo_A` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Notas_Asignaturas1_idx` (`Asignaturas_Codigo_A` ASC) VISIBLE,
  CONSTRAINT `fk_Notas_Asignaturas1`
    FOREIGN KEY (`Asignaturas_Codigo_A`)
    REFERENCES `mydb`.`Asignaturas` (`Codigo_A`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inscripcion` (
  `Estudiantes_Codigo` INT NOT NULL,
  `Asignaturas_Codigo_A` INT NOT NULL,
  PRIMARY KEY (`Estudiantes_Codigo`, `Asignaturas_Codigo_A`),
  INDEX `fk_Estudiantes_has_Asignaturas_Asignaturas1_idx` (`Asignaturas_Codigo_A` ASC) VISIBLE,
  INDEX `fk_Estudiantes_has_Asignaturas_Estudiantes_idx` (`Estudiantes_Codigo` ASC) VISIBLE,
  CONSTRAINT `fk_Estudiantes_has_Asignaturas_Estudiantes`
    FOREIGN KEY (`Estudiantes_Codigo`)
    REFERENCES `mydb`.`Estudiantes` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiantes_has_Asignaturas_Asignaturas1`
    FOREIGN KEY (`Asignaturas_Codigo_A`)
    REFERENCES `mydb`.`Asignaturas` (`Codigo_A`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



insert into Estudiantes (Codigo, Nombre, Apellido) values(9080, 'Juan', 'Perez');
insert into Estudiantes (Codigo, Nombre, Apellido) values(9081, 'Pedro', 'Rodriguez');
insert into Estudiantes (Codigo, Nombre, Apellido) values(9082, 'Maria', 'Sanchez');

insert into Asignaturas(Codigo_A, Nombre) values(1020, 'Ciencia de datos');
insert into Asignaturas(Codigo_A, Nombre) values(1021, 'Bases de datos');
insert into Asignaturas(Codigo_A, Nombre) values(1022, 'Backend Basico');


insert into Notas(Id, Nota1, Nota2, Nota3, Promedio, Id_estudiante, Asignaturas_Codigo_A) values(1,4,4,4,4,9080,1020);
insert into Notas(Id, Nota1, Nota2, Nota3, Promedio, Id_estudiante, Asignaturas_Codigo_A) values(2,4,4,4,4,9081,1022);
insert into Notas(Id, Nota1, Nota2, Nota3, Promedio, Id_estudiante, Asignaturas_Codigo_A) values(3,4,4,4,4,9081,1020);
insert into Notas(Id, Nota1, Nota2, Nota3, Promedio, Id_estudiante, Asignaturas_Codigo_A) values(4,4,4,4,4,9081,1021);


select * from Notas;

